dist: focal

language: python
python:
  - "3.8"

services:
  - mysql

env:
  - DB=mysql
  - DJANGO=3.1.3 DJANGO_SETTINGS_MODULE="eshop.settings"

before_install:
  - sudo apt update
  - sudo apt install python3-dev

# command to install dependecies

install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'create database test_db;' -u root
  - python manage.py syncdb

# command to run tests

script:
  - python manage.py test
